version: "3.3"
services:
    moon:
        image: moon
        deploy:
            restart_policy:
                condition: any
                delay: 30s
                window: 30s
            placement:
                constraints: [node.role == manager]
        secrets:
            - source: private_key
              target: private_key
              uid: '0'
              gid: '0'
              mode: 0600
            - source: registry_password
              target: registry_password
              uid: '0'
              gid: '0'
              mode: 0600
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            #- data4:/data
        environment:
            MOON_BUILD_LOCATION: localhost
            MOON_SWARM_LOCATION: docker@crtoprojects.com
            MOON_SWARM_KEYPATH: '/run/secrets/private_key'
            MOON_REGISTRY_ADDRESS: 'registry.crtoprojects.com:443'
            MOON_REGISTRY_USERNAME: 'registry'
            MOON_REGISTRY_PASSWORD_PATH: '/run/secrets/registry_password'
            MOON_REPO: https://f.pillot@gitlab.criteois.com/f.pillot/swarm-configuration-itservers.git
            MOON_BRANCH: test-new-moon
            MOON_CYCLE: 30
            MOON_DEBUG: 'true'
secrets:
    registry_password:
        file: /tmp/registry_password.txt
    private_key:
        file: /home/f.pillot/.ssh/crtoprojectscom.pem
volumes:
    data4:
