version: "3.3"
services:
    moon:
        image: bienaimable/moon2
        deploy:
            restart_policy:
                condition: any
                delay: 30s
                window: 30s
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            MOON_REPO: https://f.pillot@gitlab.criteois.com/f.pillot/swarm-configuration-itservers.git
            MOON_BRANCH: master
            MOON_CYCLE: 60
