version: "3.3"
services:
    moon:
        image: bienaimable/moon2
        deploy:
            restart_policy:
                condition: any
                delay: 120s
                window: 30s
            placement:
                constraints: [node.role == manager]
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - data:/data
        environment:
            MOON_REPO: https://f.pillot@gitlab.criteois.com/f.pillot/swarm-configuration-itservers.git
            MOON_BRANCH: master
            MOON_CYCLE: 30
volumes:
    data:
